// <auto-generated />
namespace SklepUKW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_AddDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_AddDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202104130838011_add_AddDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
