// <auto-generated />
namespace SklepUKW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_UserData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_UserData));
        
        string IMigrationMetadata.Id
        {
            get { return "202105110917591_add_UserData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
